#
# Makefile for the SONIX SD to Nand flash driver
#

obj-$(CONFIG_MTD_SNX_SD2NAND) += snx_sd2nand.o

#sn926_sd2nand-objs := core.o bus.o host.o \
			mmc.o mmc_ops.o sd.o sd_ops.o \
			sdio.o sdio_ops.o sdio_bus.o \
			sdio_cis.o sdio_io.o sdio_irq.o\
			sd2nand.o

#sn926_sd2nand-objs := sd.o sd_ops.o sd2nand.o sn926_sd.o
snx_sd2nand-objs := snx_sd2nand.o snx_sd.o
