/*
 * GPIO/gpio.h
 *
 * Author:	James_wei
 * Created:	June 8, 2009
 * Copyright:	(C) 2008 SONIX Technology, Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 */

#ifndef __SNX_REGS_GPIO_H__
#define __SNX_REGS_GPIO_H__

#include <mach/platform.h>


#define GPIO_OUT_OFFSET					0x00
#define GPIO_IN_OFFSET					0x04
#define GPIO_OE_OFFSET					0x08
#define GPIO_BYS_OFFSET					0x0C

#define GPIO_DATA_SET_OFFSET			0x10
#define GPIO_DATA_CLR_OFFSET			0x14
#define GPIO_PULL_ENB_OFFSET				0x18
#define GPIO_PULL_TYP_OFFSET				0x1C

#define GPIO_INTR_ENB_OFFSET				0x20
#define GPIO_INTR_RAW_OFFSET			0x24
#define GPIO_INTR_MSKD_OFFSET			0x28
#define GPIO_INTR_MASK_OFFSET			0x2C

#define GPIO_INTR_CLR_OFFSET				0x30
#define GPIO_INTR_MODE_OFFSET			0x34
#define GPIO_INTR_EDGE_OFFSET			0x38
#define GPIO_INTR_LEVEL_OFFSET			0x3C

#define GPIO_BOUNCE_ENABLE_OFFSET		0x40
#define GPIO_BOUNCE_PRESCALE_OFFSET		0x44

#define SNX_GPIO_OUT					(SNX_GPIO_BASE + GPIO_OUT_OFFSET)
#define SNX_GPIO_IN						(SNX_GPIO_BASE + GPIO_IN_OFFSET)
#define SNX_GPIO_OE						(SNX_GPIO_BASE + GPIO_OE_OFFSET)
#define SNX_GPIO_BYS						(SNX_GPIO_BASE + GPIO_BYS_OFFSET)
#define SNX_GPIO_DATA_SET				(SNX_GPIO_BASE + GPIO_DATA_SET_OFFSET)
#define SNX_GPIO_DATA_CLR				(SNX_GPIO_BASE + GPIO_DATA_CLR_OFFSET)
#define SNX_GPIO_PULL_ENB				(SNX_GPIO_BASE + GPIO_PULL_ENB_OFFSET)
#define SNX_GPIO_PULL_TYP				(SNX_GPIO_BASE + GPIO_PULL_TYP_OFFSET)
#define SNX_GPIO_INTR_ENB				(SNX_GPIO_BASE + GPIO_INTR_ENB_OFFSET)
#define SNX_GPIO_INTR_RAW				(SNX_GPIO_BASE + GPIO_INTR_RAW_OFFSET)
#define SNX_GPIO_INTR_MSKD				(SNX_GPIO_BASE + GPIO_INTR_MSKD_OFFSET)
#define SNX_GPIO_INTR_MASK				(SNX_GPIO_BASE + GPIO_INTR_MASK_OFFSET)
#define SNX_GPIO_INTR_CLR				(SNX_GPIO_BASE + GPIO_INTR_CLR_OFFSET)
#define SNX_GPIO_INTR_MODE				(SNX_GPIO_BASE + GPIO_INTR_MODE_OFFSET)
#define SNX_GPIO_INTR_EDGE				(SNX_GPIO_BASE + GPIO_INTR_EDGE_OFFSET)
#define SNX_GPIO_INTR_LEVEL				(SNX_GPIO_BASE + GPIO_INTR_LEVEL_OFFSET)
#define SNX_GPIO_BOUNCE_ENABLE			(SNX_GPIO_BASE + GPIO_BOUNCE_ENABLE_OFFSET)
#define SNX_GPIO_BOUNCE_PRESCALE 		(SNX_GPIO_BASE + GPIO_BOUNCE_PRESCALE_OFFSET)

#define GPIO_OUT							IO_ADDRESS(SNX_GPIO_OUT)
#define GPIO_IN 							IO_ADDRESS(SNX_GPIO_IN)
#define GPIO_OE 							IO_ADDRESS(SNX_GPIO_OE)
#define GPIO_BYS							IO_ADDRESS(SNX_GPIO_BYS)
#define GPIO_DATA_SET					IO_ADDRESS(SNX_GPIO_DATA_SET)
#define GPIO_DATA_CLR					IO_ADDRESS(SNX_GPIO_DATA_CLR)
#define GPIO_PULL_ENB					IO_ADDRESS(SNX_GPIO_PULL_ENB)
#define GPIO_PULL_TYP					IO_ADDRESS(SNX_GPIO_PULL_TYP)
#define GPIO_INTR_ENB					IO_ADDRESS(SNX_GPIO_INTR_ENB)
#define GPIO_INTR_RAW					IO_ADDRESS(SNX_GPIO_INTR_RAW)
#define GPIO_INTR_MSKD					IO_ADDRESS(SNX_GPIO_INTR_MSKD)
#define GPIO_INTR_MASK					IO_ADDRESS(SNX_GPIO_INTR_MASK)
#define GPIO_INTR_CLR					IO_ADDRESS(SNX_GPIO_INTR_CLR)
#define GPIO_INTR_MODE					IO_ADDRESS(SNX_GPIO_INTR_MODE)
#define GPIO_INTR_EDGE					IO_ADDRESS(SNX_GPIO_INTR_EDGE)
#define GPIO_INTR_LEVEL 					IO_ADDRESS(SNX_GPIO_INTR_LEVEL)
#define GPIO_BOUNCE_ENABLE				IO_ADDRESS(SNX_GPIO_BOUNCE_ENABLE)
#define GPIO_BOUNCE_PRESCALE			IO_ADDRESS(SNX_GPIO_BOUNCE_PRESCALE)


#define GPIO_INT_MODE_EDGE				0x0
#define GPIO_INT_MODE_LEVEL				0x1
#define GPIO_INT_EDGE_SINGLE				0x0
#define GPIO_INT_EDGE_BOTH				0x1
#define GPIO_INT_LEVEL_HIGHT				0x0
#define GPIO_INT_LEVEL_LOW				0x1


#endif /* __SNX_REGS_GPIO_H__ */
